### ISSUE TITLE
Setting selected property manually

### ISSUE THREAD

**Issue by gildir** [forumone/jquery.selectability.js#4]
Setting the selected property of a selectability drop down through jquery does not propagate to the drop down display until it is opened again.

**Comment by gustavderdrache** [comment]
Ultimately, it doesn't appear that there's a good (portable) way to handle this. jQuery's `.val()` method changes `selectedIndex`, which is impossible to observe reliably.

The recommended method is to use the following snippet:

``` javascript
$('select').val(foo).trigger('change')
```

Selectability will respond to the `'change'` event and update accordingly.
